chat/urls.py
from django.urls import path
from chat.controller import views, chat_views, toggles_views


app_name = 'chat'

# urlpatterns = [
#     path("", views.index, name="index"),
#     path("vehicle/options/", views.vehicle_options, name="vehicle_options"),
#     path("vehicle/set/", views.set_vehicle, name="set_vehicle"),
#     path("response/", views.chat_response, name="chat_response"),
# ]

urlpatterns = [
    path('main/', views.main, name='main'),
    path("", toggles_views.toggles_page, name="toggles_page"),
    path("vehicle/", toggles_views.vehicle_options, name="vehicle_options"),
    path("set_vehicle/", toggles_views.set_vehicle_and_go_chat, name="set_vehicle"),
    path("response/", chat_views.chat_response, name="chat_response"),
    path("info/", chat_views.info_content, name="info"),  # ✅ 모달 Ajax용 추가
]

chatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/chat/', permanent=True), name='main'),
    path('uauth/', include('uauth.urls')),
    path('chat/', include('chat.urls')),
]

uauth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from uauth.controller import views
from uauth.controller.views import MyLoginView, SendVerificationCodeView, VerifyCodeView, UserRegisterView, DeleteAccountView

app_name = 'uauth'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='uauth/login.html'), name='login'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('check_username/', views.check_username, name='check_username'),
    path('send-code/', SendVerificationCodeView.as_view(), name='send_code'),
    path('verify-code/', VerifyCodeView.as_view(), name='verify_code'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('delete_account/', DeleteAccountView.as_view(), name='delete_account'),
]

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QnA | {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
</head>
<body>
    {% include './header.html' %}
    <main class="container">
        {% if messages %}
            <div class="mt-3 alert alert-primary alert-dismissible fade show" role="alert">
                {% for message in messages %}
                	<strong>{{ message.tags }}</strong>
                    {{ message.message }}
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %} 
    
        {% block content %}
        {% endblock content %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
</body>
</html>

templates/layout/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {% for field in form %}
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}

        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}

        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}

templates/layout/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- navbar 좌측 링크 -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                </ul>
                <!-- navbar 우측 링크 -->
                <ul class="navbar-nav mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" title="{{ user.username }}">
                                {% if user.userdetail.profile %}
                                    <img src="{{ user.userdetail.profile.url }}" alt=""
                                        class="rounded-circle" width="26">
                                {% else %}
                                    <img src="/media/profile/default.jpg" alt=""
                                        class="rounded-circle" width="26">
                                {% endif %} 
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uauth:logout' %}">로그아웃</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'uauth:login' %}">로그인</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'uauth:signup' %}">회원가입</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <!-- <a class="navbar-brand" href="{% url 'autofix:index' %}">QnA</a> -->
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent"></div>
    </div>
</nav>